
version: 2

models:
    - name: order_items
      description: "An updated order items table"
      columns:
          - name: months_since_signup
            description: "Months from user signup to ordering of this order_item"
    - name: sessions
      description: "Sessionizes raw event data"