
version: 2

models:
    - name: updated_orders
      description: "An updated orders table"
      columns:
          - name: months_since_signup
            description: "Months from user signup to ordering of this order_item"
    - name: sessions
      description: "Sessionizes raw event data"