WITH PARAMS AS (
  SELECT 
    CURRENT_DATE() AS AS_OF_DATE,
    (YEAR(CURRENT_DATE()) - 2025) AS YEAR_OFFSET 
),

SHIFTED_TICKETS AS (
  SELECT
    *,
    -- Use standardized naming for shifted dates
    DATEADD(MONTH, (SELECT YEAR_OFFSET * 12 FROM PARAMS), CREATED_DATE) AS RAW_SHIFTED_CREATED,
    DATEADD(MONTH, (SELECT YEAR_OFFSET * 12 FROM PARAMS), UPDATED_DATE) AS RAW_SHIFTED_UPDATED,
    DATEADD(MONTH, (SELECT YEAR_OFFSET * 12 FROM PARAMS), RESOLVED_DATE) AS RAW_SHIFTED_RESOLVED,
    DATEADD(MONTH, (SELECT YEAR_OFFSET * 12 FROM PARAMS), DUE_DATE) AS RAW_SHIFTED_DUE
  FROM {{ ref('stg_saas__zendesk_tickets') }}
)

SELECT
  ID,
  ACCOUNT_ID,
  TICKET_ID,
  TYPE,
  SUBJECT,
  DESCRIPTION,
  PRIORITY,
  
  -- Logic: If we nulled the resolved_date, flip status back to 'open'
  IFF(
    RAW_SHIFTED_RESOLVED > P.AS_OF_DATE AND RAW_SHIFTED_RESOLVED != RAW_SHIFTED_UPDATED,
    'open',
    STATUS
  ) AS STATUS,

  CHANNEL,
  REQUESTER_ID,
  ASSIGNEE_ID,
  GROUP_ID,
  RAW_SHIFTED_CREATED AS CREATED_DATE,
  
  -- Updated Date logic (capped at today)
  IFF(RAW_SHIFTED_UPDATED > P.AS_OF_DATE, P.AS_OF_DATE, RAW_SHIFTED_UPDATED) AS UPDATED_DATE,

  -- Resolved Date logic (future becomes NULL)
  CASE 
    WHEN RAW_SHIFTED_RESOLVED > P.AS_OF_DATE THEN 
      IFF(RAW_SHIFTED_RESOLVED = RAW_SHIFTED_UPDATED, P.AS_OF_DATE, NULL)
    ELSE RAW_SHIFTED_RESOLVED 
  END AS RESOLVED_DATE,

  FIRST_RESPONSE_TIME_HOURS,
  RESOLUTION_TIME_HOURS,
  SATISFACTION_SCORE,
  SATISFACTION_COMMENT,
  TAGS,
  ACCOUNT_SEGMENT,
  BRAND_ID,
  LOCALE,
  TIMEZONE,
  RAW_SHIFTED_DUE AS DUE_DATE,
  EXTERNAL_ID,
  JIRA_ISSUE_ID

FROM SHIFTED_TICKETS
CROSS JOIN PARAMS P
WHERE RAW_SHIFTED_CREATED <= P.AS_OF_DATE 
ORDER BY CREATED_DATE DESC