WITH PARAMS AS (
  SELECT 
    CURRENT_DATE() AS AS_OF_DATE,
    (YEAR(CURRENT_DATE()) - 2025) AS YEAR_OFFSET
)

SELECT
    ID,
    ACCOUNT_ID,
    USER_ID,
    SESSION_DURATION_SECONDS,
    SESSION_DURATION_MINUTES,
    PRODUCT_ID,
    PAGES_VISITED,
    EVENTS_COUNT,
    UNIQUE_PAGES,
    BOUNCE_RATE,
    EXIT_PAGE,
    ENTRY_PAGE,
    DEVICE_TYPE,
    BROWSER,
    OS,
    COUNTRY,
    REGION,
    CITY,
    IP_ADDRESS,
    USER_AGENT,
    REFERRER,
    UTM_SOURCE,
    UTM_MEDIUM,
    UTM_CAMPAIGN,
    ACCOUNT_SEGMENT,
    PRODUCT_TIER,
    USER_COUNT,
    USER_ROLE,
    SESSION_QUALITY_SCORE,
    ERRORS_ENCOUNTERED,
    CONVERSION_EVENTS,
    
    -- Shift the Date field
    DATEADD(MONTH, P.YEAR_OFFSET * 12, SESSION_DATE) AS SESSION_DATE,
    
    -- Shift the Timestamps
    DATEADD(MONTH, P.YEAR_OFFSET * 12, SESSION_START_TIME) AS SESSION_START_TIME,
    DATEADD(MONTH, P.YEAR_OFFSET * 12, SESSION_END_TIME) AS SESSION_END_TIME

FROM {{ ref('stg_saas__sessions') }}
CROSS JOIN PARAMS P
-- Filter so sessions that haven't "happened yet" in our 2026 timeline are hidden
WHERE DATEADD(MONTH, P.YEAR_OFFSET * 12, SESSION_START_TIME) < CURRENT_TIMESTAMP()
ORDER BY SESSION_DATE DESC