version: 2

models:
  - name: order_items
    description: "An updated order items table"
    columns:
      - name: months_since_signup
        description: "Months from user signup to ordering of this order_item"
      - name: time_to_ship
        description: "Days from order created to ship date of this order_item"
  - name: sessions
    description: "Sessionizes raw event data"
    columns:
      - name: months_since_created
        description: "Months from user signup to session start"
      - name: duration
        description: "Duration of the session in seconds"
      - name: duration_minutes
        description: "Duration of the session in minutes"
      - name: had_add_to_cart_event
        description: "Clicked add to cart in product"

